@startuml

Title 查看课程实验成绩算法图

actor 显示学生课程成绩主页面
actor API服务
database 数据库存储

== 主页面 ==
显示学生课程成绩主页面->API服务:传入课程编号course_id和学号student_id
API服务->数据库存储:根据学号和课程编号、实验编号查询相应成绩
数据库存储->API服务:返回成绩数据
API服务->显示学生课程成绩主页面:返回经过完善后的成绩集合
== 每次查询请求都会访问API==

@enduml